# Generated by Django 6.0.1 on 2026-01-11 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="child",
            options={"ordering": ["name"], "verbose_name_plural": "Children"},
        ),
    ]
